import { InformationNote, InteriorHero, LinkCards, ProcessSteps, RfqSection, SectionHeading } from "@/components/Interior";
import { pageMetadata } from "@/lib/metadata";

export const metadata = pageMetadata("Business Aircraft Parts Sourcing", "Request rotables, expendables, avionics, accessories and approved hardware by part number, condition, application and document requirement.", "/parts");

export default function Page() {
  return <main>
    <InteriorHero eyebrow="PARTS / SOURCING" title="Business-aircraft parts sourcing" intro="Civilon is a sourcing partner, not a webshop. Selected items may be in stock; other requirements are sourced on demand. All availability is subject to confirmation." path="/parts" crumbs={[{label:"Home",href:"/"},{label:"Parts"}]} variant="sourcing" panelItems={["Exact part and dash number", "Quantity and aircraft application", "Acceptable condition", "Required documentation", "Required-by time and destination"]} />
    <section className="section section-tight"><div className="shell"><SectionHeading label="CATEGORIES / 01" title="Search by component family" intro="Civilon reviews rotables, expendables, avionics, accessories and approved hardware requirements for business-aircraft operations." /><LinkCards items={[{ title: "Avionics & instruments", meta: "Displays · NAV/COM · TCAS · FMS", body: "Flight-deck, navigation, communication, sensing and instrument units.", href: "/parts/avionics-instruments" }, { title: "Wheels, brakes & landing gear", meta: "Assemblies · anti-skid · actuators", body: "High-wear assemblies and landing-system components.", href: "/parts/wheels-brakes-landing-gear" }, { title: "Engine & airframe accessories", meta: "Generators · pumps · valves · hardware", body: "Engine accessories, aircraft systems and airframe equipment.", href: "/parts/engine-airframe-accessories" }]} /></div></section>
    <section className="section section-muted section-tight"><div className="shell two-column"><div><SectionHeading label="CONDITION / 02" title="State what receiving can accept" /><ul className="technical-list"><li>NE — New</li><li>NS — New Surplus</li><li>OH — Overhauled</li><li>SV — Serviceable</li><li>AR — As Removed</li></ul><p>Condition terms and supporting-document expectations are not interchangeable.</p></div><div><SectionHeading label="SOURCING / 03" title="A hybrid sourcing model" /><p className="large-copy">Requirements may be reviewed through selected stock, approved and vetted suppliers, OEM and authorized distribution channels where available, repair facilities, operators, MRO organizations and vetted surplus or teardown sources.</p><p>Trace-to-source and available supporting records are reviewed and identified with each quoted option. Documentation varies by part condition and source.</p></div></div></section>
    <section className="section section-tight"><div className="shell"><SectionHeading label="WORKFLOW / 04" title="From requirement to receiving" /><ProcessSteps steps={["Receive the exact requirement", "Define condition and documentation", "Review stock and applicable sourcing channels", "Present confirmed availability and commercial options", "Coordinate the customer-approved shipment path"]} /><InformationNote label="WARRANTY">Warranty terms vary by part condition and source and are stated with each quotation.</InformationNote><LinkCards items={[{ title: "Supported business aircraft", body: "Review primary platform coverage and additional platforms by request.", href: "/aircraft" }, { title: "Aircraft component repair management", body: "Compare repair, exchange and replacement paths.", href: "/repair-management" }, { title: "Urgent AOG coordination", body: "Use the monitored phone or WhatsApp path for a grounded aircraft.", href: "/aog-services" }]} /></div></section>
    <RfqSection sourcePage="/parts" heading="Send the part number and condition." description="Normal sourcing requests are reviewed Monday through Friday, 8:00 AM to 5:00 PM Eastern Time. For an urgent aircraft-on-ground requirement, call or WhatsApp the AOG desk." supportingPoints={["Include aircraft or engine application", "State acceptable condition and quantity", "List required documentation and destination"]} />
  </main>;
}
