import test from "node:test";import assert from "node:assert/strict";import fs from "node:fs";import path from "node:path";
const root=path.resolve(import.meta.dirname,"..");const read=(...p)=>fs.readFileSync(path.join(root,...p),"utf8");
test("quality page does not render internal certification review guidance",()=>{const source=read("app","quality-assurance","page.tsx");assert.doesNotMatch(source,/owner confirmation|certification badges|AS9120|ISO 9001/i)});
test("visible breadcrumbs use navigation labels",()=>{assert.match(read("app","parts","page.tsx"),/label:"Parts"/);assert.match(read("app","aircraft","page.tsx"),/label:"Aircraft"/);assert.match(read("app","aog-services","page.tsx"),/label:"AOG Support"/);assert.match(read("app","contact-us","page.tsx"),/label:"Contact"/)});
test("normal sourcing heroes prioritize part search and AOG hero retains urgent actions",()=>{const interior=read("components","Interior.tsx");assert.match(interior,/Start a part search/);assert.match(interior,/Call \{siteConfig\.aogPhone\}/);assert.match(interior,/WhatsApp AOG/);assert.match(interior,/siteConfig\.aogPhone/)});
test("shared connected process supports all required workflows",()=>{const interior=read("components","Interior.tsx");assert.match(interior,/process-rail/);for(const page of ["parts","aog-services","quality-assurance","repair-management"])assert.match(read("app",page,"page.tsx"),/ProcessSteps/)});
test("mobile menu exposes accessible state and suppresses urgent bar",()=>{const header=read("components","SiteHeader.tsx"),bar=read("components","MobileAogBar.tsx");assert.match(header,/aria-expanded=\{mobile\}/);assert.match(header,/Close navigation/);assert.match(header,/civilon:mobile-menu/);assert.match(bar,/civilon:mobile-menu/);assert.match(bar,/is-suppressed/)});
test("mobile trigger alignment and footer compensation use shared layout rules",()=>{const css=read("app","globals.css");assert.match(css,/\.site-nav \.menu-toggle\{margin-inline-start:auto;flex:0 0 44px\}/);assert.match(css,/body \{ padding-bottom:0; \}/);assert.match(css,/footer\{padding-bottom:calc\(24px \+ env\(safe-area-inset-bottom\)\)/)});
test("footer exposes primary routes once and labels the configured office number",()=>{const footer=read("components","SiteFooter.tsx");for(const route of ["/parts","/aog-services","/repair-management","/quality-assurance","/about-us","/contact-us"])assert.ok(footer.includes(`href="${route}"`));assert.equal((footer.match(/href="\/repair-management"/g)||[]).length,1);assert.match(footer,/Office: \{siteConfig\.officePhone\}/);assert.match(footer,/siteConfig\.officeTel/)});
