export const partCategories = {
  "avionics-instruments": { name:"Avionics & Instruments", category:"Avionics & Instruments", intro:"Source flight-deck, navigation, communication and aircraft-instrument units with the condition and paperwork your receiving team requires.", examples:["Flight displays and display units","Navigation and communication radios","Transponders and radar components","Air data and flight-control computers","Indicators, gauges and sensors","Audio and antenna components"], docs:["Confirm part-number and modification status","Match interchangeability to the aircraft configuration","Review serial-number trace and removal information","Request FAA 8130-3 or EASA Form 1 where applicable"] },
  "wheels-brakes-landing-gear": { name:"Wheels, Brakes & Landing Gear", category:"Wheels, Brakes & Landing Gear", intro:"Coordinate time-sensitive sourcing for high-wear wheel, brake and landing-gear components across business-aircraft fleets.", examples:["Wheel and brake assemblies","Brake discs and heat stacks","Landing-gear actuators","Steering and shimmy components","Tires, bearings and hardware","Gear indication and proximity components"], docs:["Confirm aircraft model, serial and installation position","Review life data where applicable","Clarify overhaul, serviceable or as-removed condition","Coordinate release and material documentation"] },
  "engine-airframe-accessories": { name:"Engine & Airframe Accessories", category:"Engine & Airframe Accessories", intro:"Find accessory, pneumatic, hydraulic, fuel and airframe components with clear condition, trace and delivery requirements.", examples:["Starters, generators and pumps","Fuel-control and ignition components","Valves and pneumatic accessories","Hydraulic pumps and actuators","Environmental-control components","Latches, controls and airframe hardware"], docs:["Provide engine or aircraft application","Confirm dash number and alternates","Review shop findings for repaired units","Compare exchange, repair and replacement options"] },
} as const;

export const aircraft = {
  beechcraft:{ name:"Beechcraft", intro:"Support for Beechcraft’s broad turboprop and light-aircraft fleet, from King Air workhorses to legacy business-jet platforms.", models:["King Air 90 / 100","King Air 200 / 250","King Air 300 / 350","Premier I / IA","Beechjet 400 / 400A","Baron and Bonanza"], notes:"King Air requests often depend on model, serial range and installation position. Include those details when available." },
  "cessna-citation":{ name:"Cessna Citation", intro:"Parts sourcing across the Citation family, with configuration-aware support for light, midsize and larger-cabin variants.", models:["Citation CJ / CJ1+ / CJ2+","CJ3+ / CJ4","Citation 500 / 550 / 560","Excel / XLS / XLS+","Sovereign and Latitude","Longitude"], notes:"Citation dash numbers and effectivity can vary by serial range and modification status; documentation is reviewed against the stated aircraft." },
  bombardier:{ name:"Bombardier", intro:"Component sourcing for Learjet, Challenger and Global fleets, including mature platforms and current long-range aircraft.", models:["Learjet 40 / 45","Learjet 60 / 70 / 75","Challenger 300 / 350","Challenger 601 / 604 / 605 / 650","Global Express / 5000 / 6000","Global 5500 / 6500 / 7500"], notes:"For Global and Challenger requirements, configuration, effectivity and documentation expectations should be stated at RFQ." },
  "dassault-falcon":{ name:"Dassault Falcon", intro:"Targeted sourcing for the Falcon fleet, where model effectivity and technical-document alignment are central to a usable quotation.", models:["Falcon 50 family","Falcon 900 family","Falcon 2000 series","Falcon 7X","Falcon 8X"], notes:"Falcon requests benefit from aircraft serial, installation location and any known modification or service-bulletin status." },
  embraer:{ name:"Embraer", intro:"Parts support for Embraer executive aircraft, from Phenom light jets through Legacy and Praetor midsize platforms.", models:["Phenom 100 family","Phenom 300 family","Legacy 450 / 500","Legacy 600 / 650","Praetor 500 / 600"], notes:"Specify the exact model, aircraft serial and acceptable condition so alternate and exchange options can be evaluated correctly." },
} as const;
