import { pageMetadata } from "@/lib/metadata";
import { siteConfig } from "@/lib/site-config";

export const metadata = pageMetadata("Privacy Policy", "How Civilon LLC handles website, RFQ, AOG and Aircraft Part Price Check information.", "/privacy-policy");

export default function PrivacyPolicyPage() {
  return <main>
    <section className="interior-hero legal-hero"><div className="shell"><span className="section-label">LEGAL / PRIVACY</span><h1>Privacy Policy</h1><p>This policy describes how Civilon LLC handles information collected through this website and its business-aviation sourcing services.</p></div></section>
    <article className="section legal-page"><div className="shell legal-prose">
      <p className="legal-meta">Last updated August 16, 2026</p>
      <section><h2>Who we are and how to contact us</h2><p>Civilon LLC, 375 Sylvan Ave, Suite 23, Englewood Cliffs, NJ 07632, operates this website. Questions or privacy requests may be sent to <a href={`mailto:${siteConfig.email}`}>{siteConfig.email}</a> or made by phone at <a href={`tel:${siteConfig.officeTel}`}>{siteConfig.officePhone}</a>.</p></section>
      <section><h2>Information we receive</h2><p>We receive information you provide in an RFQ, AOG request, contact request or Aircraft Part Price Check, including business contact details, part and aircraft context, transaction terms, notes and supporting-document selections. Price Check supporting documents are optional. We also receive limited technical information needed to operate and protect the site, such as request logs and security signals. If analytics is enabled after an approved consent decision, it may collect the limited event information described in the applicable notice.</p></section>
      <section><h2>How we use information</h2><p>We use information to respond to sourcing, repair, AOG and Price Check requests; operate and secure the service; communicate about a request; prevent abuse; maintain records; and improve our services. We do not use Price Check uploads or their contents as advertising analytics events. Civilon does not sell personal information.</p></section>
      <section><h2>Price Check documents and automated processing</h2><p>When you choose to upload a document, it is stored in private access-controlled storage, checked through the configured security workflow and may be processed with automated extraction tools to identify transaction details. Civilon staff review extracted information before it is used. Where an approved AI-assisted explanation feature is used internally, it is based on reviewed, structured analysis and does not determine price, supplier cost or margin. Human review remains required.</p></section>
      <section><h2>Service providers and disclosures</h2><p>We may use providers for hosting, databases, secure storage, malware scanning, email delivery, authentication and approved AI processing. Providers receive information only as needed to perform their service or where required by law, to protect rights and safety, or in connection with a permitted business transfer. The applicable provider and data scope depend on the request and configured service.</p></section>
      <section><h2>Retention and security</h2><p>We use reasonable technical and organizational safeguards appropriate to the service, but no transmission or storage system is completely secure. Retention periods for RFQs, abandoned requests, quarantined or rejected files, accepted work, transactional records, audit history and email records are subject to final operational and legal review. Do not upload information that is unnecessary for the requested review.</p></section>
      <section><h2>International transfers and your choices</h2><p>Information may be processed where Civilon or its service providers operate. Depending on applicable law, you may have rights to request access, correction, deletion or information about our handling of your data. Contact us using the details above; we may need to verify your request and may retain information where required or permitted by law.</p></section>
      <section><h2>Cookies, analytics and updates</h2><p>The site may use essential technologies for operation and security. Any optional Google Tag Manager or Google Analytics implementation is withheld until Civilon has made and implemented an approved consent decision; configured event collection must not include RFQ, document or Price Check fields. We may update this policy and will post the revised version here.</p></section>
    </div></article>
  </main>;
}
