import { CallAogAction, WhatsAppAogAction } from "./AogActions";
import { RfqForm } from "./RfqForm";
import { siteConfig } from "@/lib/site-config";
import { LEGACY_PART_SEARCH_ANCHOR, partSearchHref } from "@/lib/part-search-cta";
import type { CSSProperties, ReactNode } from "react";
import { PUBLIC_CTA } from "@/lib/public-cta";

type Crumb={label:string;href?:string};
type HeroVariant="standard"|"sourcing"|"aircraft"|"aog"|"quality";

export function Breadcrumbs({items,currentPath}:{items:Crumb[];currentPath:string}){const data={"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:items.map((x,i)=>({"@type":"ListItem",position:i+1,name:x.label,item:new URL(x.href||currentPath,siteConfig.url).toString()}))};return <><nav className="breadcrumbs" aria-label="Breadcrumb">{items.map((x,i)=><span key={x.label}>{i>0&&" / "}{x.href?<a href={x.href}>{x.label}</a>:x.label}</span>)}</nav><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(data)}}/></>}

// searchHref lets a page that keeps its own service-specific intake — repair
// management, documentation review — hold the hero action on that form. Every
// ordinary sourcing page takes the default, which is the Buy Request page
// wherever Buy intake is open and the same-page anchor when it is not.
export function InteriorHero({eyebrow,title,intro,path,crumbs,variant="standard",panelItems=[],secondaryHref,secondaryLabel,searchHref=partSearchHref(LEGACY_PART_SEARCH_ANCHOR),primaryLabel}:{eyebrow:string;title:string;intro:string;path:string;crumbs:Crumb[];variant?:HeroVariant;panelItems?:string[];secondaryHref?:string;secondaryLabel?:string;searchHref?:string;primaryLabel?:string}){
 const panelTitle=variant==="sourcing"?"What to send":variant==="aircraft"?"Platform context":variant==="quality"?"Document review":"Monitored AOG contact",hasPanel=variant!=="standard"||panelItems.length>0;
 const resolvedPrimaryLabel=primaryLabel??(path==="/repair-management"?"Start a Repair Request":path==="/quality-assurance"?"Start a Documentation Request":PUBLIC_CTA.buy);
 return <section className={`interior-hero hero-${variant}`} data-mobile-aog-suppress><div className="shell"><Breadcrumbs items={crumbs} currentPath={path}/><div className={`interior-hero-grid ${hasPanel?"has-panel":""}`}><div className="interior-hero-copy"><span className="section-label light">{eyebrow}</span><h1>{title}</h1><p>{intro}</p>{variant!=="aog"&&<div className="interior-actions"><a className="button button-primary" href={searchHref}>{resolvedPrimaryLabel}</a>{secondaryHref&&<a className="hero-secondary" href={secondaryHref}>{secondaryLabel} →</a>}<a className="hero-urgent-link" href="/aog-services">Aircraft on ground? AOG support →</a></div>}</div>{hasPanel&&<aside className={`hero-context-panel ${variant==="aog"?"prominent-aog-actions":""}`} aria-label={panelTitle}><span>{panelTitle}</span>{variant==="aog"?<><strong>{siteConfig.aogPhone}</strong><p>Have the part number, quantity, aircraft location and required-by time ready.</p><CallAogAction className="button button-primary" source_page={path}>{PUBLIC_CTA.callAog}</CallAogAction><WhatsAppAogAction className="button button-whatsapp" source_page={path}>{PUBLIC_CTA.whatsAppAog}</WhatsAppAogAction></>:<ul>{panelItems.map(x=><li key={x}>{x}</li>)}</ul>}</aside>}</div></div></section>
}
export function SectionHeading({label,title,intro}:{label:string;title:string;intro?:string}){return <div className="interior-heading"><span className="section-label">{label}</span><h2>{title}</h2>{intro&&<p>{intro}</p>}</div>}
export function ProcessSteps({steps}:{steps:(string|{title:string;description?:string})[]}){return <ol className="process-rail" style={{"--process-count":steps.length} as CSSProperties}>{steps.map((step,i)=>{const s=typeof step==="string"?{title:step}:step;return <li key={s.title}><span>{String(i+1).padStart(2,"0")}</span><div><h3>{s.title}</h3>{s.description&&<p>{s.description}</p>}</div></li>})}</ol>}
function cardAction(href:string){if(href.startsWith("/parts"))return "View category";if(href.startsWith("/aircraft"))return "View aircraft";if(href==="/repair-management")return "Review service";if(href==="/aog-services")return "Review AOG support";return "Review details"}
export function LinkCards({items,variant="cards"}:{items:{title:string;body:string;href:string;meta?:string;cta?:string}[];variant?:"cards"|"rows"}){return <div className={`link-cards link-${variant}`}>{items.map((x,i)=><a href={x.href} key={x.href}><span className="link-index">0{i+1}</span><div><h3>{x.title}</h3>{x.meta&&<small>{x.meta}</small>}<p>{x.body}</p></div><b className="card-action">{x.cta||cardAction(x.href)} <span aria-hidden="true">→</span></b></a>)}</div>}
export function InformationNote({label,children}:{label:string;children:ReactNode}){return <div className="information-note" role="note"><span>{label}</span><p>{children}</p></div>}
export function RfqSection({eyebrow="START / RFQ",heading="Tell the sourcing desk what you need.",description="Provide the part number and the details you know. For urgent needs, mark the request AOG or contact the desk directly.",supportingPoints=[],compact=false,...props}:React.ComponentProps<typeof RfqForm>&{eyebrow?:string;heading?:string;description?:string;supportingPoints?:string[];compact?:boolean}){return <section className={`section rfq-section ${compact?"rfq-compact":""}`} id="rfq"><div className="shell rfq-layout"><div><span className="section-label">{eyebrow}</span><h2>{heading}</h2><p>{description}</p>{supportingPoints.length>0&&<ul className="rfq-points">{supportingPoints.map(x=><li key={x}>{x}</li>)}</ul>}</div><RfqForm {...props} idPrefix={(props.idPrefix||props.sourcePage||"page").replaceAll("/","-")}/></div></section>}
