import { CallAogAction, WhatsAppAogAction } from "./AogActions";
import { RfqForm } from "./RfqForm";

export function Breadcrumbs({ items }: { items: { label: string; href?: string }[] }) { const data = { "@context":"https://schema.org", "@type":"BreadcrumbList", itemListElement: items.map((x,i)=>({"@type":"ListItem",position:i+1,name:x.label,item:x.href})) }; return <><nav className="breadcrumbs" aria-label="Breadcrumb">{items.map((x,i)=><span key={x.label}>{i>0 && " / "}{x.href?<a href={x.href}>{x.label}</a>:x.label}</span>)}</nav><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(data)}} /></>; }
export function InteriorHero({ eyebrow, title, intro, path, urgent=false }: {eyebrow:string;title:string;intro:string;path:string;urgent?:boolean}) { return <section className="interior-hero"><div className="shell"><Breadcrumbs items={[{label:"Home",href:"/"},{label:title}]} /><span className="section-label light">{eyebrow}</span><h1>{title}</h1><p>{intro}</p>{urgent && <div className="hero-actions"><CallAogAction className="button button-primary" source_page={path}>Call AOG desk</CallAogAction><WhatsAppAogAction className="button button-whatsapp" source_page={path}>WhatsApp AOG</WhatsAppAogAction></div>}</div></section>; }
export function SectionHeading({ label, title, intro }: {label:string;title:string;intro?:string}) { return <div className="interior-heading"><span className="section-label">{label}</span><h2>{title}</h2>{intro && <p>{intro}</p>}</div>; }
export function ProcessSteps({ steps }: {steps:string[]}) { return <ol className="process-grid">{steps.map((step,i)=><li key={step}><span>{String(i+1).padStart(2,"0")}</span><p>{step}</p></li>)}</ol>; }
export function LinkCards({ items }: {items:{title:string;body:string;href:string}[]}) { return <div className="link-cards">{items.map(x=><a href={x.href} key={x.href}><h3>{x.title}</h3><p>{x.body}</p><b>Explore →</b></a>)}</div>; }
export function RfqSection(props: React.ComponentProps<typeof RfqForm>) { return <section className="section rfq-section" id="rfq"><div className="shell rfq-layout"><div><span className="section-label">START / RFQ</span><h2>Send the requirement.<br/>We’ll work the channels.</h2><p>Provide the part number and the details you know. For urgent needs, mark the request AOG or contact the desk directly.</p></div><RfqForm {...props} idPrefix={(props.idPrefix || props.sourcePage || "page").replaceAll("/", "-")} /></div></section>; }
