import type { Metadata } from "next";
import { CallAogAction } from "@/components/AogActions";
import { InteriorHero, SectionHeading } from "@/components/Interior";
import { partSearchHref } from "@/lib/part-search-cta";
import { PUBLIC_CTA } from "@/lib/public-cta";

const description = "Civilon is a private parts-sourcing desk for business aviation. One accountable counterparty for sourcing, documentation and delivery — established 2012 in Englewood Cliffs, NJ.";
export const metadata: Metadata = { title: "About Civilon | Business Aircraft Parts Sourcing, Englewood Cliffs NJ", description, alternates: { canonical: "/about-us" }, robots: { index: process.env.NEXT_PUBLIC_ALLOW_INDEXING === "true", follow: true }, openGraph: { title: "About Civilon | Business Aircraft Parts Sourcing, Englewood Cliffs NJ", description, url: "/about-us", siteName: "Civilon", images: [{ url: "/og.png", width: 1200, height: 630, alt: "Civilon business aviation parts sourcing" }] } };

const modelPoints = [
  { title: "You deal with one counterparty.", body: "Civilon sources the part and sells it to you under a single quotation — part number, stated condition, included documentation, price and delivery terms." },
  { title: "Buyers and suppliers stay separated.", body: "Suppliers respond privately to Civilon; identities and commercial details are not exchanged." },
  { title: "The paperwork is part of the part.", body: "Each quotation identifies the release and supporting documentation available — FAA 8130-3 or EASA Form 1 where applicable, condition codes stated clearly." },
  { title: "A person answers.", body: "The AOG line and WhatsApp are monitored by a live person, 24/7/365." },
];
const facts = ["Established 2012 — Englewood Cliffs, New Jersey", "More than a decade in aviation sourcing and freight logistics", "Worldwide coordination, subject to destination and compliance requirements", "24/7/365 — AOG line answered by a live person"];

export default function Page() { return <main>
  <InteriorHero eyebrow="COMPANY / ABOUT" title="Built to be accountable." intro="Civilon is a business-aircraft parts sourcing company in Englewood Cliffs, New Jersey. When you buy through Civilon, you buy from Civilon — one desk answers for the search, the offer, the paperwork and the delivery." path="/about-us" crumbs={[{ label: "Home", href: "/" }, { label: "About Civilon" }]} />
  <section className="section section-tight"><div className="shell about-copy"><SectionHeading label="THE PROBLEM WE WORK ON" title="Parts buying has too many middlemen and not enough ownership." /><p className="large-copy">A typical parts search ends in a chain: a broker quoting another broker, a stock line nobody has confirmed, paperwork that arrives after the part. When something goes wrong, everyone in the chain points at someone else.</p><p className="large-copy">Civilon was established in 2012 to remove that ambiguity. We don&apos;t forward you to a seller — we become the seller. Our desk locates the part through vetted channels, validates the offer and the available records, and issues one Civilon quotation. If you accept, the deal, the documents and the delivery are our responsibility to coordinate.</p><p className="section-qualifier">Availability, condition and documentation are confirmed per request.</p></div></section>
  <section className="section section-muted section-tight"><div className="shell about-copy"><SectionHeading label="SOURCING + FREIGHT, ONE DESK" title="A parts desk that thinks like a freight desk." /><p className="large-copy">The team behind Civilon comes from freight and logistics operations as much as from parts sourcing. That background shapes how we work: routing, customs and export documentation, and delivery coordination aren&apos;t services we outsource and hope for — they&apos;re the part of the job we know best.</p><p className="large-copy">It&apos;s why a Civilon offer states delivery terms alongside price and condition, and why an AOG request gets a transport answer, not just a stock answer.</p></div></section>
  <section className="section section-tight"><div className="shell"><SectionHeading label="THE CIVILON MODEL" title="Private by design." intro="Nothing at Civilon is a public listing. Every request is handled directly by our desk." /><div className="about-model-grid">{modelPoints.map((point) => <article key={point.title}><h3>{point.title}</h3><p>{point.body}</p></article>)}</div><p className="section-qualifier">Civilon does not certify parts and does not determine airworthiness, regulatory approval, authenticity or fitness; supporting documentation varies by part and source.</p></div></section>
  <section className="about-facts" aria-label="Civilon facts"><div className="shell"><ul>{facts.map((fact) => <li key={fact}>{fact}</li>)}</ul></div></section>
  <section className="section section-muted section-tight"><div className="shell about-copy"><SectionHeading label="STRAIGHT ANSWERS" title="We'd rather be clear than impressive." /><p className="large-copy">Civilon is not a public marketplace, not a listing site, and not a certification body. We don&apos;t publish inventory counts we can&apos;t stand behind, and we don&apos;t guarantee what only a release certificate can show. What we commit to is narrower and more useful: one accountable desk that tells you what a part is, what records come with it, what it costs, and how it gets to you.</p><div className="interior-actions about-actions"><a className="button button-primary" href={partSearchHref()}>{PUBLIC_CTA.buy}</a><CallAogAction className="button button-outline" source_page="/about-us">Call the AOG Desk</CallAogAction></div></div></section>
</main>; }
