export const includeReasonCodes = [
  "EXACT_MATCH",
  "GOVERNED_PART_RELATIONSHIP",
  "CONDITION_MATCH",
  "TRANSACTION_TYPE_MATCH",
  "DATE_ACCEPTABLE",
  "DOCUMENTATION_COMPARABLE",
  "WARRANTY_COMPARABLE",
  "CORE_TERMS_COMPARABLE",
  "AOG_CONTEXT_COMPARABLE",
] as const;

export const excludeReasonCodes = [
  "WRONG_PART",
  "UNVERIFIED_PART_RELATIONSHIP",
  "CONDITION_MISMATCH",
  "TRANSACTION_TYPE_MISMATCH",
  "TOO_OLD",
  "DOCUMENTATION_MISMATCH",
  "CORE_TERMS_NOT_COMPARABLE",
  "WARRANTY_NOT_COMPARABLE",
  "AOG_CONTEXT_NOT_COMPARABLE",
  "CURRENCY_NOT_COMPARABLE",
  "SOURCE_RELIABILITY",
  "PERMITTED_USE_RESTRICTION",
  "DUPLICATE_OBSERVATION",
  "OTHER_REVIEWED_REASON",
] as const;

export type IncludeReasonCode = (typeof includeReasonCodes)[number];
export type ExcludeReasonCode = (typeof excludeReasonCodes)[number];
